import Head from 'next/head'
import Image from 'next/image'

import { Container, Box, makeStyles } from '@material-ui/core'
import { HomeClickableCard, ThemedButton, ThemeContext } from '@@components'

const useStyles = makeStyles(theme => ({
  container: {
    minHeight: 'calc(100vh - 64px)',
    padding: '0 0.5rem',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: 'calc(100vh - 64px)',
    [theme.breakpoints.down('sm')]: {
      minHeight: '100%',
      height: '100%',
    }
  },
  main: {
    padding: '5rem 0',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    margin: 0,
    lineHeight: 1.15,
    fontSize: '4rem',
    textAlign: 'center',
    '& a': {
      color: theme.palette.primary.dark,
      textDecoration: 'none',
      transition: 'color 0.15s ease'
    },
    '& a:hover, a:focus, a:active': {
      color: theme.palette.secondary.dark,
      textDecoration: 'underline'
    }
  },
  description: {
    textAlign: 'center'
  },
  code: {
    background: '#e3e3e3',
    borderRadius: '5px',
    padding: '0.75rem',
    fontSize: '1.1rem',
    fontFamily: `Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace`
  },
  footer: {
    width: '100%',
    height: '100px',
    borderTop: `1px solid ${theme.palette.primary.dark}`,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    '& a': {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      flexGrow: 1
    }
  },
  logo: {
    height: '1em',
    marginLeft: '0.5rem'
  },
  grid: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: '3rem',
    maxWidth: '800px',
    [theme.breakpoints.down('sm')]: {
      maxWidth: '100%',
      flexDirection: 'column'
    }
  }
}))



export const Home = () => {
  const classes = useStyles()
  return (
    <Container className={classes.container}>
      <Head>
        <title>Voyager | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
        <h1 className={classes.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <ThemedButton />

        <p className={classes.description}>
          Get started by editing{' '}
          <code className={classes.code}>pages/index.js</code>
        </p>

        <Box className={classes.grid}>
          <HomeClickableCard title="Documentation" description="Find in-depth information about Next.js features and API." href="https://nextjs.org/docs" />
          <HomeClickableCard title="Learn" description="Learn about Next.js in an interactive course with quizzes!" href="https://nextjs.org/learn" />
          <HomeClickableCard title="Examples" description="Discover and deploy boilerplate example Next.js projects." href="https://github.com/vercel/next.js/tree/master/examples" />
          <HomeClickableCard title="Deploy" description="Instantly deploy your Next.js site to a public URL with Vercel." href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" />
        </Box>
      </main>

      <footer className={classes.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={classes.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </Container>
  )
}

export default Home